### ISSUE TITLE
 Cannot assign to read only property 'name' of function (app, opts)

### ISSUE THREAD

**Issue by majintao** [pipi32167/pomelo-http-plugin#4]
C:\Users\Administrator\git\brodcast\brodcast\node_modules\pomelo-http-plugin\lib\components\http.js:85
Http.name = '**Http**';
          ^
TypeError: Cannot assign to read only property 'name' of function (app, opts) {
  opts = opts || {};
  this.app = app;
  this.http = express();
  // self.logger.info('H...<omitted>...
}
    at Object.<anonymous> (C:\Users\Administrator\git\brodcast\brodcast\node_modules\pomelo-http-plugin\lib\components\http.js:85:11
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\Administrator\git\brodcast\brodcast\node_modules\pomelo\lib\application.js:662:17
    at Array.forEach (native)
    at Object.Application.use (C:\Users\Administrator\git\brodcast\brodcast\node_modules\pomelo\lib\application.js:652:37)

插件在Linxu上能够正常使用，可是在Mac和Windows上均包这个错误！请作者处理下

**Comment by pipi32167** [comment]
node、pomelo、pomelo-http-plugin的版本分别是？

**Comment by majintao** [comment]
好像都是最新的

**Comment by pipi32167** [comment]
不要好像啊。。我需要知道是什么环境，然后配置环境进行测试。

**Comment by pipi32167** [comment]
node是0.12.x？pomelo是 1.1.9? pomelo-http-plugin是0.0.22 ?

**Comment by pipi32167** [comment]
新的ECMAScript标准里面增加了function.name只读属性，所以造成了报错。已fix。
